"""initial schema

Revision ID: 70aacc833547
Revises: 
Create Date: 2026-04-06 22:46:03.779723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '70aacc833547'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tase_id', sa.String(length=20), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name_he', sa.String(length=200), nullable=True),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pays_dividend', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_index(op.f('ix_stocks_tase_id'), 'stocks', ['tase_id'], unique=True)
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=True)
    op.create_table('dividends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('declared_date', sa.Date(), nullable=True),
    sa.Column('amount_ils', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('dividend_yield_at_declaration', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('maya_filing_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('maya_filing_id'),
    sa.UniqueConstraint('stock_id', 'ex_date', name='uq_dividend_stock_exdate')
    )
    op.create_index(op.f('ix_dividends_ex_date'), 'dividends', ['ex_date'], unique=False)
    op.create_index(op.f('ix_dividends_stock_id'), 'dividends', ['stock_id'], unique=False)
    op.create_table('fundamentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('operating_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('eps', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('capex', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('dividends_paid', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('shareholders_equity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('payout_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fcf_payout_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'fiscal_year', name='uq_fundamental_stock_year')
    )
    op.create_index(op.f('ix_fundamentals_stock_id'), 'fundamentals', ['stock_id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('week52_high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('week52_low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trade_date', name='uq_price_stock_date')
    )
    op.create_index(op.f('ix_prices_stock_id'), 'prices', ['stock_id'], unique=False)
    op.create_index(op.f('ix_prices_trade_date'), 'prices', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_trade_date'), table_name='prices')
    op.drop_index(op.f('ix_prices_stock_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_fundamentals_stock_id'), table_name='fundamentals')
    op.drop_table('fundamentals')
    op.drop_index(op.f('ix_dividends_stock_id'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_ex_date'), table_name='dividends')
    op.drop_table('dividends')
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_tase_id'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
